<?php
$tech = $this->getProduct()->getData('features');
$info = json_decode($tech, true);
$info = [];
$count = 0;
?>
<div style="width: 700px; margin:auto;" id="features_container">
    <?php if (count($info) > 0) : ?>
    <?php foreach ($info as $i) : ?>
        <div class="specs_row" id="features_<?= $count ?>">
            <div class="draggable-handle"></div>
            <?php var_dump($i); die(); ?>
            <label for="feat_n_<?= $count ?>">Label <?= $count ?></label>
            <input style="width:15%; margin-left:5px;" id="feat_n_<?= $count ?>" data-form-part="product_form" value="<?= $i['name'] ?>" name="features[<?= $count ?>]['name']" />
            <label for="feat_d_<?= $count ?>">Feature <?= $count ?></label>
            <textarea id="feat_d_<?= $count ?>" style="width:60%;" data-form-part="product_form" name="features[<?= $count?>['desc']"><?= $i['desc'] ?></textarea>
        <a class="delete_icon" src="javascript:void(0)" onclick="deleteFeature('features_<?= $count ?>')"></a>
        </div>
        <?php $count++ ?>
    <?php endforeach ?>
    <?php endif ?>
</div>
<button onclick="addFeature()">Add Feature</button>

<script>
    var $q = jQuery.noConflict();
    $q( document ).ready(function() {
        $q('#features_container').sortable({
            handle: '.draggable-handle',
            revert: 300,
            placeholder: "ui-state-highlight myHover",
            tolerance: "intersect",
        }).disableSelection();
    });
    function addFeature()
    {
        var counts = $q('#features_container input').length;
        $q('#features_container').append
        ('<div id="features_'+counts+'"><div class="draggable-handle"></div>' +
            '<label for="feat_n_'+counts+'">Label '+counts+'</label>'+
            '<input id="feat_n_'+counts+'" style="width:15%; margin-right:5px;" data-form-part="product_form" value="" name="features['+counts+'][\'name\']" />'+
            '<label for="feat_d_'+counts+'">Feature '+counts+'</label>'+
            '<textarea id="feat_d_'+counts+'" style="width:60%; vertical-align: top;" data-form-part="product_form" name="features['+counts+'][\'desc\']"></textarea>'+
            "<a class=\"delete_icon\" src=\"javascript:void(0)\" onclick=\"deleteFeature(features_"+counts+")\"></a>" +
            "<br/></div>");
    }

    function deleteFeature(h)
    {
        $q('#'+h).remove();
    }
</script>